name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK on Ubuntu Latest
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          python3-pip \
          libffi-dev \
          libssl-dev \
          libsqlite3-dev \
          libpng-dev \
          libfreetype6-dev \
          libz-dev \
          libjpeg-dev \
          pkg-config \
          libncurses6 \
          libncurses-dev

    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install cython
        pip install buildozer

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: kivy-apk
        path: bin/*.apk
        
